name: Shopify Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
          # Clear cookies using Puppeteer before running Lighthouse
      - name: Clear Cookies
        run: |
          node -e "
            const puppeteer = require('puppeteer');
            (async () => {
              const browser = await puppeteer.launch();
              const page = await browser.newPage();
              await page.goto('https://theme-blackbytt-poc.myshopify.com');
              const client = await page.target().createCDPSession();
              await client.send('Network.clearBrowserCookies');
              await browser.close();
            })();
          "
    - name: Lighthouse
      uses: shopify/lighthouse-ci-action@v1
      with:
        access_token: "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"
        store: "theme-blackbytt-poc.myshopify.com"
        lhci_min_score_accessibility: 0.85
        password: "saylyo"
