name: Shopify Lighthouse CI
on: [push]

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install dependencies to use Puppeteer
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Puppeteer
        run: npm install puppeteer

      # Clear cookies using Puppeteer before running Lighthouse
      - name: Clear Cookies
        run: |
          node -e "
            const puppeteer = require('puppeteer');
            (async () => {
              const browser = await puppeteer.launch();
              const page = await browser.newPage();
              await page.goto('https://theme-blackbytt-poc.myshopify.com');
              const client = await page.target().createCDPSession();
              await client.send('Network.clearBrowserCookies');
              await browser.close();
            })();
          "

      - name: Run Lighthouse CI
        uses: shopify/lighthouse-ci-action@v1
        with:
          access_token: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
          password: ${{ secrets.SHOPIFY_PASSWORD }}
          store: "theme-blackbytt-poc.myshopify.com"
          lhci_min_score_accessibility: 0.85
